CREATE TABLE USER_ACCOUNT (
    USER_NO NUMBER(10) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(10) NOT NULL,
    USER_PW VARCHAR(10) NOT NULL,
    USER_NAME VARCHAR(10) NOT NULL,
    USER_ADDRESS VARCHAR(20),
    USER_PHONENUMBER VARCHAR(20),
    USER_EMAIL VARCHAR(20)
);


CREATE TABLE USER_BOARD (
    BOARD_NO NUMBER(10) NOT NULL PRIMARY KEY,
    BOARD_TITLE VARCHAR(20) NOT NULL,
    BOARD_CONTENT VARCHAR(50),
    BOARD_HIT NUMBER(10),
    BOARD_DATE DATE
);


