CREATE TABLE BOARD_JAVA (
SEQ NUMBER,
ID VARCHAR2(30),
NAME VARCHAR2(15),
SUBJECT VARCHAR2(100),
CONTENT VARCHAR2(500),
LOGTIME DATE
)

CREATE SEQUENCE BOARD_JAVA_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 99999
NOCYCLE
NOCACHE
NOORDER;