CREATE TABLE LOCATIONS2 AS SELECT * FROM locations;
alter table locations2 rename column location_id to loc_id;
-- 문제1
SELECT 
JOB_ID,
SUM(SALARY) AS SALARYSUM
FROM employees
GROUP BY job_id;
--HAVING SUM(job_id)

-- EX5
SELECT 
E.EMPLOYEE_ID,
D.DEPARTMENT_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- EX6
SELECT 
E.EMPLOYEE_ID,
D.DEPARTMENT_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- EX7
SELECT 
E.EMPLOYEE_ID,
D.DEPARTMENT_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = E.DEPARTMENT_ID;


-- 문제2
SELECT D.DEPARTMENT_ID, L.CITY
FROM DEPARTMENTS D
JOIN LOCATIONS L
ON D.LOCATION_ID = I.LOCATION_ID;
--USING(LOCATIONS_ID);


-- EX8
SELECT D.DEPARTMENT_ID, L.CITY
FROM DEPARTMENTS D
FULL JOIN LOCATIONS L
ON D.LOCATION_ID = I.LOCATION_ID;


-- EX9
SELECT 
E.EMPLOYEE_ID,
D.DEPARTMENT_ID,
D.DEPARTMENT_NAME,
D.MANAGER_ID
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = E.DEPARTMENT_ID AND E.MANAGER_ID = D.MANAGER_ID;


-- 문제3
SELECT E.LAST_NAME,
L.CITY,
D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = 'Oxford' OR L.CITY = 'Seattle'
ORDER BY CITY;

-- EX10
SELECT
L2.CITY,
D.DEPARTMENT_NAME
FROM LOCATIONS2 L2
JOIN DEPARTMENTS D
ON L2.LOC_ID = D.LOCATION_ID;


-- EX11
SELECT DISTINCT(A.EMPLOYEE_ID), A.LAST_NAME FROM EMPLOYEES A
JOIN EMPLOYEES B ON B.MANAGER_ID=A.EMPLOYEE_ID;


-- EX14
SELECT 
FIRST_NAME,
E.JOB_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN JOBS J
ON E.JOB_ID = J.JOB_ID;

-- 문제4
SELECT
E.EMPLOYEE_ID AS 사원번호,
E.FIRST_NAME AS 사원이름,
D.DEPARTMENT_NAME AS 부서이름,
L.CITY AS 도시,
L.STREET_ADDRESS AS 도시주소,
C.COUNTRY_NAME AS 나라이름
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID
WHERE STREET_ADDRESS LIKE '%Ch%' OR STREET_ADDRESS LIKE '%Sh%' OR STREET_ADDRESS LIKE '%Rd%'
ORDER BY 나라이름, 도시

