-- 문제1)
CREATE VIEW V_VIEW2
AS SELECT 
EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY >= 5000 AND SALARY <= 10000;


-- 문제2)
CREATE VIEW V_VIEW3
AS SELECT
EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES A
JOIN DEPARTMENTS B 
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHERE A.DEPARTMENT_ID IN (10, 90)
ORDER BY EMPLOYEE_ID;



-- 문제3 
CREATE VIEW V_VIEW4
AS SELECT
EMPLOYEE_ID, FIRST_NAME, TO_CHAR(SALARY,'FM999,999,999,999')  AS SALARY , TO_CHAR(HIRE_DATE, 'DL') AS 날짜, C.CITY ,DEPARTMENT_NAME
FROM EMPLOYEES A
JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
JOIN LOCATIONS C
ON B.LOCATION_ID = C.LOCATION_ID
WHERE A.DEPARTMENT_ID IN (10, 90)
ORDER BY EMPLOYEE_ID;

-- 문제4 
CREATE TABLE BOOKSHOP
(isbn varchar2(10) PRIMARY KEY-- 기본키 (제약조건명 : PISBN)
,title varchar2(50) NOT NULL -- 널값 허용X (제약조건명 : CTIT), 책제목
,author varchar2(50) -- 저자
,price number -- 금액
,company varchar2(30)); -- 출판사
--DROP TABLE BOOKSHOP;
INSERT INTO BOOKSHOP(ISBN, TITLE, AUTHOR, PRICE, COMPANY) VALUES('is001', '자바3일완성', '김자바', '25000', '야메루출판사');
INSERT INTO BOOKSHOP(ISBN, TITLE, AUTHOR, PRICE, COMPANY) VALUES('pa002', 'JSP달인되기', '이달인', '28000', '공갈닷컴');
INSERT INTO BOOKSHOP(ISBN, TITLE, AUTHOR, PRICE, COMPANY) VALUES('or003', '오라클무작정따라하기', '박따라', '23500', '야메루출판사');

CREATE SEQUENCE idx_seq
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999
    NOCYCLE
    NOCACHE
    NOORDER;

CREATE TABLE BOOKORDER
(idx number PRIMARY KEY-- 기본키, 일련번호
,isbn varchar2(10) -- 외래키 (제약조건명 : FKISBN), bookshop의 isbn의 자식키
,qty number
, CONSTRAINT FK_ISBN FOREIGN KEY(ISBN) REFERENCES BOOKSHOP(ISBN)
); -- 수량
INSERT INTO BOOKORDER(IDX, ISBN, QTY) VALUES(1, 'is001', 2);
INSERT INTO BOOKORDER(IDX, ISBN, QTY) VALUES(2, 'or003', 3);
INSERT INTO BOOKORDER(IDX, ISBN, QTY) VALUES(3, 'pa002', 5);
INSERT INTO BOOKORDER(IDX, ISBN, QTY) VALUES(4, 'is001', 3);
INSERT INTO BOOKORDER(IDX, ISBN, QTY) VALUES(5, 'or003', 10);

CREATE VIEW BS_VIEW
AS SELECT A.TITLE AS 책제목, A.AUTHOR AS 저자, TO_CHAR(SUM(B.QTY * A.PRICE),'FM999,999,999,999') AS 총판매금액
FROM BOOKSHOP A
JOIN BOOKORDER B
ON A.ISBN = B.ISBN
GROUP BY A.TITLE, A.AUTHOR;

--문제5
SELECT A.FIRST_NAME AS 이름, B.DEPARTMENT_NAME, MAX(A.SALARY) AS MAXSALARY
FROM EMPLOYEES A
JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
JOIN (SELECT EMPLOYEES_ID ) C
GROUP BY B.DEPARTMENT_NAME ;

--문제6
SELECT A.FIRST_NAME AS  사원이름, B.DEPARTMENT_NAME, (SALARY * 12 * NVL(A.COMMISSION_PCT, 1)) AS 연봉 
FROM EMPLOYEES A
JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHERE ROWNUM <= 5
ORDER BY 연봉 DESC;


SELECT * FROM V_VIEW2;
SELECT * FROM V_VIEW3;
SELECT * FROM V_VIEW4;
SELECT * FROM BS_VIEW;