SELECT * FROM TAB;
SELECT * FROM USER_SEQUENCES;
SELECT * FROM EMPLOYEES;
DESC EMPLOYESS;


SELECT EMPLOYEE_ID AS "사원번호" , 
FIRST_NAME ||' '|| LAST_NAME AS "이 름" ,
SALARY*12 AS "연 봉" FROM EMPLOYEES;

SELECT LASTNAME || 'is a ' || substr(JOB_ID,0, 2) || ' ' ||substr(JOB_ID, 4)
 FROM EMPLOYEES;
 
 
 -- 문제1
 SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
 
 -- 문제2
 SELECT LAST_NAME, HIRE_DATE, DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=10 OR DEPARTMENT_ID=90;
 
 -- 문제3
 SELECT FIRST_NAME ||' '|| LAST_NAME
 , '$' || SALARY
 , DEPARTMENT_ID
  FROM EMPLOYEES;


--문제4
SELECT=]


FIRST_NAME ||' '|| LAST_NAME AS "이 름" ,
JOB_ID, SALARY
FROM EMPLOYEES
WHERE ( JOB_ID = 'SA_REP' OR JOB_ID='AD_PRES')
AND SALARY >= 10000;

--문제5
 SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
 
 
 SELECT EMPLOYEE_ID,FIRST_NAME ||' '|| LAST_NAME AS "이 름" ,
 HIRE_DATE
 FROM EMPLOYEES
 WHERE HIRE_DATE>='2005-01-01' AND HIRE_DATE <= '2005-12-31';


-- 문제1
 SELECT FIRST_NAME, SALARY
 FROM EMPLOYEES
 ORDER BY SALARY DESC;
 
 
-- 문제2
 SELECT CONCAT(LAST_NAME, FIRST_NAME ) 
 , LENGTH(CONCAT(FIRST_NAME,LAST_NAME)) AS LENGTH
  FROM EMPLOYEES WHERE FIRST_NAME LIKE '%n';

-- 문제3
SELECT CONCAT(SUBSTR(SYSDATE,0, 6), '01'), -- 첫째일 구하기,
LAST_DAY(SYSDATE),-- 마지막 날 구하기,
SYSDATE,
LAST_DAY(SYSDATE) - SYSDATE || '일 남음' AS RESULT2
FROM DUAL;


-- 문제4
SELECT LAST_NAME, TO_char(HIRE_DATE, 'DD" -"MM"월" "-"YYYY')
FROM EMPLOYEES
WHERE HIRE_DATE < '2005-01-01';

-- 문제5
SELECT COUNT(*) FROM EMPLOYEES WHERE commission_pct IS NULL;


-- 문제 6
SELECT 
EMPLOYEE_ID AS 사원번호,
first_name AS 사원명,
CASE WHEN SALARY > 20000 THEN '중급'
WHEN SALARY > 10000 THEN '초급'
ELSE '고급' END AS 구분
FROM EMPLOYEES;

-- 문제7
SELECT EMPLOYEE_ID,
LAST_NAME,
SALARY,
CASE WHEN commission_pct IS NOT NULL
THEN '$ ' || TO_CHAR(SALARY*12*commission_pct, 'FM999,999,999,999')
ELSE '$ ' || TO_CHAR(SALARY*12, 'FM999,999,999,999')
END AS 연봉,
commission_pct
FROM EMPLOYEES;

-- 문제8
SELECT 
EMPLOYEE_ID,
LAST_NAME,
CASE WHEN MANAGER_ID IS NULL
THEN 1000
ELSE MANAGER_ID END AS MANAGER_ID
FROM EMPLOYEES;


