
SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello PL/SQL!!');
END;

DECLARE
    NAME VARCHAR(10);
    AGE NUMBER(4) := 25;

BEGIN
    NAME := '홍길동';
    DBMS_OUTPUT.PUT_LINE('NAME : ' || NAME);
    DBMS_OUTPUT.PUT_LINE('AGE : ' || AGE);
END;
/

DECLARE
    V_NO DEPARTMENTS.DEPARTMENT_ID%TYPE := 50;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_NO : ' || V_NO);
END;
/



DECLARE
    V_DEPT DEPARTMENTS%ROWTYPE;
BEGIN
    SELECT 
    *
    -- DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
    INTO V_DEPT
    FROM DEPARTMENTS 
    WHERE DEPARTMENT_ID = 50;
    
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT_ID : ' || V_DEPT.DEPARTMENT_ID);
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT_NAME : ' || V_DEPT.DEPARTMENT_NAME);
    DBMS_OUTPUT.PUT_LINE('MANAGER_ID : ' || V_DEPT.MANAGER_ID);
    DBMS_OUTPUT.PUT_LINE('LOCATION_ID : ' || V_DEPT.LOCATION_ID);
END;
/

DECLARE 
    PI CONSTANT NUMBER := 3.141592;
    APPLE VARCHAR2(10) NOT NULL := 'hong';
    ID VARCHAR2(10) NOT NULL := 'hong';
    PWD VARCHAR2(10) NOT NULL DEFAULT '1234';
BEGIN
    DBMS_OUTPUT.PUT_LINE('PI : ' || PI);
    DBMS_OUTPUT.PUT_LINE('APPLE : ' || APPLE);
    DBMS_OUTPUT.PUT_LINE('ID : ' || ID);
    DBMS_OUTPUT.PUT_LINE('PWD : ' || PWD);
END;
/


-- IF문
DECLARE
    NUM NUMBER := 15;
BEGIN
    IF MOD(NUM, 2) = 1 THEN
        DBMS_OUTPUT.PUT_LINE(NUM || '는 홀수이다.');
    END IF;
END;
/


-- IF ELSE문
DECLARE
    NUM NUMBER := 16;
BEGIN
    IF MOD(NUM, 2) = 0 THEN
        DBMS_OUTPUT.PUT_LINE(NUM || '는 짝수이다.');
    ELSE 
        DBMS_OUTPUT.PUT_LINE(NUM || '는 홀수이다.');
    END IF;
END;
/

-- IF ELSIF 문
DECLARE
    SCORE NUMBER := 87;
BEGIN
    IF SCORE >= 90 THEN 
        DBMS_OUTPUT.PUT_LINE('A 학점');
    ELSIF SCORE >= 80 THEN 
        DBMS_OUTPUT.PUT_LINE('B 학점');
    ELSIF SCORE >= 70 THEN 
        DBMS_OUTPUT.PUT_LINE('C 학점');
    ELSIF SCORE >= 60 THEN 
        DBMS_OUTPUT.PUT_LINE('D 학점');
    ELSE
        DBMS_OUTPUT.PUT_LINE('F 학점');
    END IF;
END;
/

-- CASE WHEN
DECLARE
    SCORE NUMBER := 87;
BEGIN
    CASE TRUNC(SCORE/10)
        WHEN 9 THEN DBMS_OUTPUT.PUT_LINE('A 학점');
        WHEN 8 THEN DBMS_OUTPUT.PUT_LINE('B 학점');
        WHEN 7 THEN DBMS_OUTPUT.PUT_LINE('C 학점');
        WHEN 6 THEN DBMS_OUTPUT.PUT_LINE('D 학점');
        ELSE DBMS_OUTPUT.PUT_LINE('F 학점');
    END CASE;
END;
/

DECLARE 
    SCORE NUMBER := 87;
BEGIN
    CASE
        WHEN SCORE >= 90 THEN DBMS_OUTPUT.PUT_LINE('A 학점');
        WHEN SCORE >= 80 THEN DBMS_OUTPUT.PUT_LINE('B 학점');
        WHEN SCORE >= 70 THEN DBMS_OUTPUT.PUT_LINE('C 학점');
        WHEN SCORE >= 60 THEN DBMS_OUTPUT.PUT_LINE('D 학점');
        ELSE DBMS_OUTPUT.PUT_LINE('F 학점');
    END CASE;
END;
/

-- 기본 LOOP
DECLARE
    NUM NUMBER := 0;
BEGIN
    WHILE NUM < 4 LOOP
        DBMS_OUTPUT.PUT_LINE(NUM);
        NUM := NUM + 1;
    END LOOP;
END;
/

-- FOR LOOP
BEGIN
    FOR i IN 0..4 LOOP
        DBMS_OUTPUT.PUT_LINE(i);
    END LOOP;
END;
/

